#spring:
#  datasource:
#    taiwan:
#      jdbc-url: jdbc:mysql://localhost:3306/d_taiwan??useSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      username: game
#      password: uu5!^%jg
#    billing:
#      jdbc-url: jdbc:mysql://localhost:3306/taiwan_billing?useSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      username: game
#      password: uu5!^%jg
#    cain:
#      jdbc-url: jdbc:mysql://localhost:3306/taiwan_cain?useSSL=false?useSSL=false&characterEncoding=utf-8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: game
#      password: uu5!^%jg
#    cain2nd:
#      jdbc-url: jdbc:mysql://localhost:3306/taiwan_cain_2nd?useSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      username: game
#      password: uu5!^%jg
#    houtai:
#      jdbc-url: jdbc:mysql://124.220.33.239:3306/houtai?useSSL=false&characterEncoding=utf-8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: game
#      password: morelove0813...
spring:
  datasource:
    taiwan:
      jdbc-url: jdbc:mysql://124.220.33.239:3306/d_taiwan?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
    billing:
      jdbc-url: jdbc:mysql://124.220.33.239:3306/taiwan_billing?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
    cain:
      jdbc-url: jdbc:mysql://124.220.33.239:3306/taiwan_cain?useSSL=false&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
    cain2nd:
      jdbc-url: jdbc:mysql://124.220.33.239:3306/taiwan_cain_2nd?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
    houtai:
      jdbc-url: jdbc:mysql://124.220.33.239:3306/houtai?useSSL=false&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      max-lifetime: 120000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 1111
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 600000
logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath:cc/buckler/dnf/mapper/*.xml
  type-aliases-package: cc.buckler.dnf.pojo