spring:
  datasource:
    taiwan:
      jdbc-url: jdbc:mysql://121.4.61.37:3306/d_taiwan?characterEncoding=UTF-8&useSSL=false&Timezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
    billing:
      jdbc-url: jdbc:mysql://121.4.61.37:3306/taiwan_billing?characterEncoding=UTF-8&useSSL=false&Timezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
server:
  port: 11111
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 600000
logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath*:cc/buckler/dnf/mapper/*.xml