#spring:
#  datasource:
#    taiwan:
#      jdbc-url: jdbc:mysql://localhost:3306/d_taiwan?characterEncoding=UTF-8&useSSL=false&Timezone=UTC
#      driver-class-name: com.mysql.jdbc.Driver
#      username: game
#      password: uu5!^%jg
#    billing:
#      jdbc-url: jdbc:mysql://localhost:3306/taiwan_billing?characterEncoding=UTF-8&useSSL=false&Timezone=UTC
#      driver-class-name: com.mysql.jdbc.Driver
#      username: game
#      password: uu5!^%jg
spring:
  datasource:
    taiwan:
      jdbc-url: jdbc:mysql://121.4.61.37:3306/d_taiwan?characterEncoding=UTF-8&useSSL=false&Timezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
    billing:
      jdbc-url: jdbc:mysql://121.4.61.37:3306/taiwan_billing?characterEncoding=UTF-8&useSSL=false&Timezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: game
      password: morelove0813...
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 1800000
      connection-test-query: SELECT 1
server:
  port: 1111
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 600000
logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath*:cc/buckler/dnf/mapper/*.xml
  type-aliases-package: cc.buckler.dnf.pojo